CREATE TABLE airports (
    code     VARCHAR(10)  NOT NULL,
    name     VARCHAR(255) NOT NULL,
    city     VARCHAR(255) NOT NULL,
    country  VARCHAR(255) NOT NULL,
    timezone VARCHAR(100) NOT NULL,
    CONSTRAINT pk_airports PRIMARY KEY (code)
);

CREATE TABLE flights (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    flight_number    VARCHAR(20)    NOT NULL,
    airline          VARCHAR(255)   NOT NULL,
    origin_code      VARCHAR(10)    NOT NULL,
    destination_code VARCHAR(10)    NOT NULL,
    departure_time   TIMESTAMP      NOT NULL,
    arrival_time     TIMESTAMP      NOT NULL,
    price            NUMERIC(10, 2) NOT NULL,
    aircraft         VARCHAR(50),
    CONSTRAINT pk_flights PRIMARY KEY (id),
    CONSTRAINT fk_flights_origin FOREIGN KEY (origin_code) REFERENCES airports (code),
    CONSTRAINT fk_flights_destination FOREIGN KEY (destination_code) REFERENCES airports (code)
);

CREATE INDEX idx_flights_origin_code ON flights (origin_code);
CREATE INDEX idx_flights_destination_code ON flights (destination_code);
CREATE INDEX idx_flights_departure_time ON flights (departure_time);
CREATE INDEX idx_flights_route_departure ON flights (origin_code, destination_code, departure_time);
